using Photon.Pun;
using UnityEngine;

namespace ONM.Mods
{
	internal class Crash
	{
		//idk what oddie was on ts doesnt even work lamfo
		public static void CrashServer()
		{
			PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
			PhotonNetwork.DestroyAll();
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.9f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
			PhotonNetwork.Instantiate("PhotonVR/Player", GorillaTagger.Instance.transform.position + new Vector3(0f, 0.4f, 0f), GorillaTagger.Instance.transform.rotation, 0, null);
		}
		
		public static void CrashPerson(Photon.Realtime.Player owner)
		{
			for (int i = 0; i < 55; i++)
			{
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.SetMasterClient(PhotonNetwork.LocalPlayer);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.DestroyPlayerObjects(owner);
				PhotonNetwork.CloseConnection(owner);
				PhotonNetwork.CloseConnection(owner);
			}
		}
	}
}
